name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18, 20, 22 ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          NODEJS_VERSION: ${{ matrix.node }}
      - run: yarn run test
